export const GET_STANDART_GAMEBOARD = 'gameboard.GET_STANDART_GAMEBOARD'
export const GET_STANDART_GAMEBOARD_SUCCESS = 'gameboard.GET_STANDART_GAMEBOARD_SUCCESS'
export const GET_STANDART_GAMEBOARD_ERROR = 'gameboard.GET_STANDART_GAMEBOARD_ERROR'
