export const GET_STANDART_GAMEBOARD = 'gameboard.GET_STANDART_GAMEBOARD'
export const GET_STANDART_GAMEBOARD_SUCCESS = 'gameboard.GET_STANDART_GAMEBOARD_SUCCESS'
export const GET_STANDART_GAMEBOARD_ERROR = 'gameboard.GET_STANDART_GAMEBOARD_ERROR'

export const GET_PLAYERS = 'gameboard.GET_PLAYERS'
export const GET_PLAYERS_SUCCESS = 'gameboard.GET_PLAYERS_SUCCESS'
export const GET_PLAYERS_ERROR = 'gameboard.GET_PLAYERS_ERROR'

export const UPDATE_PLAYER_HISTORY = 'gameboard.UPDATE_PLAYER_HISTORY'

export const GET_CONFIRMATION_BEFORE_BUY_SUCCESS = 'gameboard.GET_CONFIRMATION_BEFORE_BUY_SUCCESS'
